name: Build Scraper Redis Docker Image

# Schedule the job to run at 2 AM every day (UTC time)
on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily

  # Allows manual workflow trigger
  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        description: Push to Registry
        required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # Checkout the repository
        - name: Checkout code
            uses: actions/checkout@v3
