name: Build Scraper Redis Docker Image

# Schedule the job to run at 2 AM every day (UTC time)
on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily

  # Allows manual workflow trigger
  workflow_dispatch:
    inputs:
      PUSH_TO_REGISTRY:
        type: boolean
        description: Push to Registry
        required: true
        default: false

      DOCKER_TAG:
        type: string
        description: Docker Tag
        required: true
        default: 'NIGHTLY'

      USE_BRANCH_AS_DOCKER_TAG:
        type: boolean
        description: Use branch name as docker tag
        required: true
        default: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Checkout code from the repository
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        - name: Determine current branch
          run: |
            if [[ "${{ inputs.USE_BRANCH_AS_DOCKER_TAG }}" == 'true' && $GITHUB_REF != 'refs/heads/main' ]]; then
                echo "BUILD_TAG=swatkat1977/rummage-scraper_redis:${GITHUB_REF##*/}" >> "$GITHUB_ENV"
                echo "|=> Docker tag : ${GITHUB_REF##*/}"
            else
              if [[ "${{ inputs.DOCKER_TAG }}" = "NIGHTLY" ]]; then
                echo "|=> Docker tag : NIGHTLY"
                echo "BUILD_TAG=swatkat1977/rummage-scraper_redis:NIGHTLY" >> "$GITHUB_ENV"
              else
                echo "|=> Docker tag : ${{ inputs.DOCKER_TAG }}"
                echo "BUILD_TAG=swatkat1977/rummage-scraper_redis:${{ inputs.docker_tag }}" >> "$GITHUB_ENV"
              fi
            fi